### ISSUE TITLE
Feature Proposal: Audience claim metric re-labelling 

### ISSUE THREAD

**Issue by tobbbles** [weeco/cortex-gateway#7]
Hey team, great project here!

I have an interesting use case that I think this gateway could solve with new functionality on the `audience` part of the token.

### Some context:
I run a Cortex cluster as a HA and long-term metric solution. But my multi-tenancy set-up is different to most; I instead run a fixed cluster of Prometheus & Cortex components, and my 'tenants' are actually specified in metric labels. (As an example, my `http_request_duration_seconds` metric would be divided into series by a `client` label, being sourced from multiple applications. (e.g. _application a_ serves metrics for _client alpha_ and _client bravo_. And _application b_ serves metrics for _client charlie_)

## Proposal
My proposal to help with this albeit obscure usecase is to utilise the Audience claim as a label key-value map to enforce a set of rules around read and write paths.

**Read Path**
I foresee the most popular use for this feature being in the read path. Being able to narrow the query result set by enforcing customisable labels. An example token may look like:

```json
{
  "tenant_id": "organization",
  "aud": {
    "client": "alpha"
  }
}
```

The gateway is then responsible for parsing the incoming query, parsing the labels, and enforcing the `instance="customer-alpha"` label on all incoming queries. A project that exists already in a similar fashion to this is [prom-label-proxy](https://github.com/openshift/prom-label-proxy) however labels are configured on startup of the service and cannot be dynamically processed.

**Write Path**
The write path will likely not benefit from this feature, as the existing concept of relabelling from the Remote Write API exists. There might be a use case for setting an audience label map on writing, but I cannot identify it currently 

---

_Note: I am mostly looking for feedback and input to validate whether this would be a valid contribution, and gauge whether this use case exists in the wild, before forking and looking at working on a feature here._

**Comment by weeco** [comment]
Hi @tobbbles , thanks for taking the time writing down your usecase in detail. I believe this is a rather specific usecase and since this gateway basically consists of 100 loc I'd recommend you to hard fork it for your own usecase. To provide at least a bit feedback to your idea: I would use a non standard claim (not `audience`). If you want to use the audience claim for some reason, keep this CVE in mind: https://github.com/dgrijalva/jwt-go/issues/422

In the future we may want to enhance the gateway so that it can validate a token for either read or write path. This way you can issue write only or read only tokens. Additionally we want to add the possibility to add IP ranges in the claim that can be filtered on.
